{
  "internal_server": "خطای داخلی رخ داده است، لطفا پس از مدتی دوباره امتحان کنید."
}